Lesson3
amsak1983/TestGuru pull request #2
Opened 2023-06-25 20:20 UTC by amsak1983

ура

2023-06-26 07:07 UTC, VidgarVii requested changes

2023-06-26 07:07 UTC, VidgarVii commented on test-guru/config/initializers/version.rb
> +  VERSION = '0.1.0'.freeze
frozen_string_literal уже замораживает строку

2023-06-26 07:07 UTC, VidgarVii commented on test-guru/db/migrate/20230625192900_add_part_number_to_products.rb
> +  def change
пустые миграции создают бардак в коде. Это еще хуже чем лишние миграции

2023-06-26 07:07 UTC, VidgarVii commented on test-guru/db/migrate/20230625194733_add_null_constraint.rb
> +    change_column_null(:tests, :title, false)
не стоит добавлять отдельные миграции для изменения полей в одном ПР. Миграции всегда являются опасным местом в ПО. Так как меняют схему базы. И всегда стараются минимизировать кол-во миграций.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу. Все остальные миграции являются обычным оверхедом

Пример
```
t.string :title, null: false 
```
Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

2023-06-26 07:07 UTC, VidgarVii commented on test-guru/db/schema.rb
> +    t.index ["category_id"], name: "index_tests_on_category_id"
для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

2023-06-26 07:07 UTC, VidgarVii commented on test-guru/db/migrate/20230625200000_add_references.rb
> +  end
чтобы не было ответов без вопросов и вопросов без тестов и т.д для связей надо добавить опцию null false

2023-06-27 06:29 UTC, VidgarVii requested changes

2023-06-27 06:29 UTC, VidgarVii commented on test-guru/app/models/categorie.rb
> +class Categorie < ApplicationRecord
Categor**y**

2023-06-27 06:29 UTC, VidgarVii commented on test-guru/config/initializers/version.rb
> +module TestGuru
ПР из прошлого урока надо было с мержить в main ветку. И тут он не должен фигурировать

2023-06-27 06:29 UTC, VidgarVii commented on test-guru/db/migrate/20230625184358_create_tests.rb
> +      t.string :name_autor, null: false
автор это юзер. Таблица для юзеров уже есть. Согласно нормализации данных нужна связь с таблицей юзеров, а не обычное текстовое поле

2023-06-27 06:29 UTC, VidgarVii commented on test-guru/db/migrate/20230625184358_create_tests.rb
> +      t.string :name_autor, null: false
нет связи с категорией

2023-06-27 06:29 UTC, VidgarVii commented on test-guru/db/migrate/20230625200000_add_references.rb
> +  end
вот это https://github.com/amsak1983/TestGuru/pull/2#discussion_r1241717121 замечание не было исправлено

2023-07-04 15:53 UTC, closed without merging

2023-07-14 15:57 UTC, amsak1983 commented
с